apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $.Values.name }}
  name:  {{ $.Values.name }}
spec:
  replicas:  {{ $.Values.resources.replicaCount }}
  selector:
    matchLabels:
      app:  {{ $.Values.name }}
  template:
    metadata:
      labels:
        app:  {{ $.Values.name }}
    spec:
      containers:
      - image: "{{ .Values.global.registry }}/{{ .Values.global.image }}:{{ .Values.global.tag }}"
        name:  {{ $.Values.name }}
        ports:
        - containerPort: 80
          name: {{ $.Values.name }}
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
          - name: HARBOR_API
            valueFrom:
              secretKeyRef:
                name: {{ $.Values.harbor.existingSecret }}
                key: HARBOR_API_URL
          - name: HARBOR_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ $.Values.harbor.existingSecret }}
                key: HARBOR_USERNAME
          - name: HARBOR_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $.Values.harbor.existingSecret }}
                key: HARBOR_PASSWORD
          - name: TAGS
            valueFrom:
              configMapKeyRef:
                name: {{ $.Values.name }}-env
                key: TAGS
{{- if $.Values.global.existingRegisrySecret }}          
      imagePullSecrets:
      - name: {{ $.Values.global.existingRegisrySecret }}
{{ end }}