apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ $.Values.name }}
  annotations:
    kubernetes.io/tls-acme: 'false' 
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - secretName: {{ .Values.ingress.tls.existingSecret }}
      hosts:
      {{- range $hostname := .Values.ingress.hostnames }}
      - {{ $hostname }}
      {{- end }}
  rules:
    {{- range $hostname := .Values.ingress.hostnames }}
    - host: {{ $hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.name }}
                port:
                  number: 80
    {{- end }}